# Generated by Django 4.0.1 on 2022-01-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='complete',
            new_name='completed',
        ),
    ]
