# Generated by Django 4.0.1 on 2022-01-11 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mymodel_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 16, 59, 34, 843006, tzinfo=utc)),
        ),
    ]
